spring:
  config:
    import:
      - classpath:/application-jwt-secret.yml
      #- classpath:/application-db.yml
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/marico
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  ## Email Send Configuration_SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: "apptivemarico@gmail.com"
    password: "nytd pitq nvgb nhym"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: Info


server:
  port: 8080
