spring:
  config:
    import:
      - classpath:/application-jwt-secret.yml
      - classpath:/application-db.yml
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  ## Email Send Configuration_SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: "apptivemarico@gmail.com"
    password: "nytd pitq nvgb nhym"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: INFO

server:
  port: 8080
